<?xml version="1.0" encoding="UTF-8"?><testrun name="StringUtilsTest.testLevenshteinDistance" project="Diginamic-TP-tests-unitaires" tests="1" started="1" failures="1" errors="0" ignored="0">
  <testsuite name="fr.diginamic.utils.StringUtilsTest" time="0.015" displayname="StringUtilsTest" uniqueid="[engine:junit-jupiter]/[class:fr.diginamic.utils.StringUtilsTest]">
    <testcase name="testLevenshteinDistance" classname="fr.diginamic.utils.StringUtilsTest" time="0.015" displayname="testLevenshteinDistance()" uniqueid="[engine:junit-jupiter]/[class:fr.diginamic.utils.StringUtilsTest]/[method:testLevenshteinDistance()]">
      <failure>
        <expected>0</expected>
        <actual>5</actual>
        org.opentest4j.AssertionFailedError: expected: &lt;0&gt; but was: &lt;5&gt;&#13;
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)&#13;
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)&#13;
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)&#13;
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)&#13;
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)&#13;
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:531)&#13;
	at fr.diginamic.utils.StringUtilsTest.testLevenshteinDistance(StringUtilsTest.java:13)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)&#13;
&#13;

      </failure>
    </testcase>
  </testsuite>
</testrun>
